# GitHub Release configuration
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - renovate[bot]
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bugfix
        - bug
    - title: 🧰 Maintenance
      labels:
        - chore
        - maintenance
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔒 Security
      labels:
        - security
    - title: ⚡ Performance
      labels:
        - performance
        - optimization
    - title: 🧪 Testing
      labels:
        - test
        - testing
    - title: 🏗️ Infrastructure
      labels:
        - infrastructure
        - ci
        - cd
    - title: Other Changes
      labels:
        - "*"