version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: runnerhub-backend
    ports:
      - "8300:8300"
    environment:
      - NODE_ENV=production
      - PORT=8300
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - runnerhub
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8300/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://192.168.1.16:8300
        - VITE_WS_URL=ws://192.168.1.16:8300
    container_name: runnerhub-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - runnerhub

networks:
  runnerhub:
    driver: bridge

volumes:
  runner_data: