groups:
  - name: github_runnerhub_performance
    rules:
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, job_response_time_seconds_bucket) > 1.0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds"

      - alert: LowThroughput
        expr: rate(jobs_completed_total[5m]) < 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low throughput detected"
          description: "Job completion rate is {{ $value }} jobs per second"

      - alert: HighResourceUtilization
        expr: cpu_utilization_percent > 80 or memory_utilization_percent > 85
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "High resource utilization"
          description: "Resource utilization is above threshold"

      - alert: DatabaseConnectionPoolExhaustion
        expr: db_connection_pool_utilization > 90
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "DB connection pool utilization: {{ $value }}%"
