name: Simple Test

on:
  push:
    branches: [ main ]

jobs:
  test-runner:
    runs-on: [self-hosted, docker, runnerhub]
    
    steps:
    - name: Check runner
      run: |
        echo "✅ Runner is working!"
        echo "Runner name: $RUNNER_NAME"
        echo "Runner OS: $RUNNER_OS"
        pwd
        ls -la