name: Test Runner

on:
  workflow_dispatch:
  push:
    branches: [ test/runner-* ]

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Test Runner
      run: |
        echo "✅ Runner is working!"
        echo "Runner name: $RUNNER_NAME"
        echo "Runner OS: $RUNNER_OS"
        echo "Runner temp: $RUNNER_TEMP"
        echo "GitHub workspace: $GITHUB_WORKSPACE"
        
    - name: Show environment
      run: |
        echo "=== Environment Variables ==="
        env | sort
        
    - name: Docker test
      run: |
        echo "=== Docker Version ==="
        docker --version
        echo "=== Docker Info ==="
        docker info